== 証明責務

構築したモデルに対して証明しなければならないシークエント．

latexmath:[c]:: 定数
latexmath:[v]:: 変数
latexmath:[A(c)]:: latexmath:[c] に関連する公理の集合．
latexmath:[I(c, v)]:: latexmath:[c, v] に関連する不変条件の集合．
latexmath:[v' = E(c, v)]:: before-after predicateで表したイベント．
latexmath:[v] がイベントのアクションの結果 latexmath:[v'] に遷移した，という意味．
latexmath:[G(c, v)]:: イベントのガード
latexmath:[w]:: 具象変数. vの次でw?
latexmath:[J(c, v, w)]:: 具象不変条件. Iの次でJ?
latexmath:[H(c, w)]:: 具象イベントのガード．Gの次でH?
latexmath:[w' = F(c, w)]:: before-after predicateで表したイベント．Eの次でF?
latexmath:[v' = K(c)]:: before-after predicateで表した初期化イベント．
latexmath:[w' = L(c)]:: before-after predicateで表した具象初期化イベント．

=== モデル単体の性質に関するもの

==== INV

[stem]
++++
\begin{array}{|l|c|}\hline
 A(c)            & \\
 I(c, v)         & \\
 G(c, v)         & \name{INV} \\
\vdash           & \\
 I_i(c, E(c, v)) & \\
\hline
\end{array}
++++

イベントの前後で不変条件が保存されていることを証明するためのシークエント．

==== DLF (Deadlock freedom)

[stem]
++++
\begin{array}{|l|c|}\hline
 A(c)                           & \\
 I(c, v)                        & \\
\vdash                          & \name{DLF} \\
 G_1(c, v) \vee \dots G_m(c, v) & \\
\hline
\end{array}
++++

公理と不変条件が成立しているならばガードのうちの少なくとも一つが真である．
つまり，いずれかのイベントは実行可能である．

=== Refinementに関するもの

==== GRD

[stem]
++++
\begin{array}{|l|c|}\hline
 A(c)       & \\
 I(c, v)    & \\
 J(c, v, w) & \name{GRD} \\
 H(c, w)    & \\
\vdash      & \\
 G_i(c, v)  & \\
\hline
\end{array}
++++

具象ガードが抽象ガードより強いことを示すために証明しなければならないシークエント．
抽象イベントが有効にならない場合には具象イベントも有効にならないことを意味する．

==== INV

[stem]
++++
\begin{array}{|l|c|}\hline
 A(c)                      & \\
 I(c, v)                   & \\
 J(c, v, w)                & \name{INV} \\
 H(c, w)                   & \\
\vdash                     & \\
 J_i(c, E(c, v), F(c, w))  & \\
\hline
\end{array}
++++



==== INV

[stem]
++++
\begin{array}{|l|c|}\hline
 A(c)                & \\
 J(c, v, w)          & \name{INV} \\
\vdash               & \\
 J_i(c, K(c), L(c))  & \\
\hline
\end{array}
++++

初期イベントに関連するINV．初期イベントにはガードがないのでGRD関連の前件がない．

<<<