== 推論規則
本文中で言及される推論規則について．

=== MON
[stem]
++++
\rule
  {\meta{H1} \vdash \meta{G}}
  {\meta{H1}, \meta{H2} \vdash \meta{G}}
  {MON}
++++

２つの仮説 latexmath:[\meta{H1}，\meta{H2}] のもとで
latexmath:[\meta{G}] が成り立つことを証明するためには，
latexmath:[\meta{H1}] のみのもとで latexmath:[\meta{G}] が成り立つことを証明すれば十分である．

=== P2
[stem]
++++
\rule
  {\vphantom{l}}
  {\meta{H}, \meta{n} \in \NAT \vdash \meta{n}+1 \in \NAT}
  {P2}
++++

ペアノの第二公理．公理であるため前件は存在しない．
MONを適用して次のようにも表現できる (というかこちらが一般的?)

[stem]
++++
\rule
  {\vphantom{l}}
  {\meta{n} \in \NAT \vdash \meta{n}+1 \in \NAT}
  {P2}
++++

=== INC
[stem]
++++
\rule
  {\vphantom{l}}
  {\meta{n} \lt \meta{m} \vdash \meta{n}+1 \leq \meta{m}}
  {INC}
++++

=== DEC
[stem]
++++
\rule
  {\vphantom{l}}
  {\meta{n} \leq \meta{m} \vdash \meta{n}-1 \lt \meta{m}}
  {DEC}
++++

=== OR_R1, OR_R2
[stem]
++++
\rule
  {\meta{H} \vdash \meta{P}}
  {\meta{H} \vdash \meta{P} \vee \meta{Q}}
  {OR\_R1}
\quad
\rule
  {\meta{H} \vdash \meta{Q}}
  {\meta{H} \vdash \meta{P} \vee \meta{Q}}
  {OR\_R2}
++++

orなので latexmath:[\meta{P}, \meta{Q}] どちらかだけ
latexmath:[\meta{H}] のもとで成り立つことが証明できればよい．

=== P1
[stem]
++++
\rule
  {\vphantom{l}}
  {\vdash 0 \in \NAT}
  {P1}
++++

ペアノの第一公理．

=== P3
[stem]
++++
\rule
  {\vphantom{l}}
  {\meta{n} \in \NAT \vdash 0 \le \meta{n}}
  {P3}
++++

ペアノの第三公理．

=== OR_L
[stem]
++++
\rule
  {\meta{H}, \meta{P} \vdash \meta{R} \qquad \meta{H}, \meta{Q} \vdash \meta{R}}
  {\meta{H}, \meta{P} \vee \meta{Q} \vdash \meta{R}}
  {OR_L}
++++

latexmath:[\meta{P}]あるいはlatexmath:[\meta{Q}]が成り立つ
ときにlatexmath:[\meta{R}]が成り立つことを証明するにはそれぞれ
を独立して証明すればよい．

前件が二つあることに注意する．

#これってlatexmath:[\meta{H}]はMONで消しちゃってもいいような気も…．

<<<
